apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter
spec:
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
        - name: greeter
          image: "greeter:0.0.1-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "768Mi"
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              port: 8080
              path: /actuator/health/readiness
---
apiVersion: v1
kind: Service
metadata:
  name: greeter
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: greeter
