global:
    scrape_interval: 10s
    evaluation_interval: 10s

scrape_configs:
#    - job_name: 'prometheus'
#      static_configs:
#          - targets: ['host.docker.internal:9090']
#    - job_name: 'tempo'
#      static_configs:
#        - targets: ['host.docker.internal:3200']
  - job_name: 'app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
