apiVersion: v2
appVersion: 2.12.0
dependencies:
- alias: minio
  condition: minio.enabled
  name: minio
  repository: https://charts.min.io/
  version: 5.0.14
- alias: grafana-agent-operator
  condition: metaMonitoring.grafanaAgent.installOperator
  name: grafana-agent-operator
  repository: https://grafana.github.io/helm-charts
  version: 0.3.19
- alias: rollout_operator
  condition: rollout_operator.enabled
  name: rollout-operator
  repository: https://grafana.github.io/helm-charts
  version: 0.14.0
description: Grafana Mimir
home: https://grafana.com/docs/helm-charts/mimir-distributed/latest/
icon: https://grafana.com/static/img/logos/logo-mimir.svg
kubeVersion: ^1.20.0-0
name: mimir-distributed
version: 5.3.0
