# uses the spring.config.import to connect to spring cloud config
spring:
  application:
    name: billboard    # name of the application that is used to identify the app to the config server
  config:
    import: "configserver:http://localhost:8888" # only works in boot 2.4 or later
    #import: "optional:configserver:http://localhost:8888" # adding optional allows app to startup even if config server is not available

---

#!
#! This configuration is only active when the app is running on Kubernetes.
#!
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
    import: "configserver:http://config-server.config-server.svc.cluster.local:8888"
