apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      serviceAccountName: "spring-cloud"
      containers:
      - image: asaikali/message-service:latest
        imagePullPolicy: Always
        name: message-service
        ports:
          - containerPort: 8080
        env:
          - name: "JAVA_OPTS"
            value: "-XshowSettings:vm -XX:MaxRAMPercentage=75.0"
        resources:
          requests:
            cpu: 1000m
            memory: 1G
          limits:
            cpu: 1000m
            memory: 1G
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            port: 8080
            path: /alive
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          httpGet:
            port: 8080
            path: /actuator/health



