apiVersion: v1
kind: Service
metadata:
  labels:
    app: message-service
  name: message-service
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: message-service
  type: NodePort
