apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: a-record

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - a-record-message-service/k8s/message-service.yaml
  - a-record-billboard-client/k8s/billboard-client.yaml

