spring:
  application:
    name: greeter     # name of the application that is used to identify the app to the config server
  cloud:
    config:
      # network location of the config server
      uri: http://localhost:8888  # only works in boot 2.3 or earlier unless special legacy processing mode is configured
      # make app startup fail if it can't connect to config server rather than start
      # with no configs
      fail-fast: true
