spring:
  threads:
    virtual:
      enabled: true
services:
  hello: "/hello"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
