### mcp initialize
POST http://localhost:3001/mcp
Content-Type: application/json
Accept: application/json, text/event-stream

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "initialize",
  "params": {
    "protocolVersion": "2025-06-18",
    "capabilities": {
      "roots": {
        "listChanged": true
      },
      "sampling": {},
      "elicitation": {}
    },
    "clientInfo": {
      "name": "ExampleClient",
      "title": "Example Client Display Name",
      "version": "1.0.0"
    }
  }
}

> {%
  if (response.headers['mcp-session-id']) {
    client.global.set("mcp_session_id", response.headers['mcp-session-id']);
    console.log("MCP Session ID set: " + response.headers['mcp-session-id']);
  } else {
    console.log("MCP Session ID header missing in response");
  }
%}

### Initialized notification request
POST http://localhost:3001/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
Mcp-Session-Id: {{mcp_session_id}}

{
  "jsonrpc": "2.0",
  "method": "notifications/initialized"
}
