apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: discovery

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - native-message-service/k8s/message-service.yaml
  - native-billboard-client/k8s/billboard-client.yaml

