version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.6.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.6.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:9.2.1
    ports:
      - "3000:3000"
    networks:
      - loki

  prometheus:
    image: prom/prometheus:v2.39.1
    ports:
      - "9090:9090"

  openzipkin:
    image: openzipkin/zipkin:2.23
    ports:
      - "9411:9411"


