apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: upstream/static
    contents:
      - path: tailscale
        git:
          url: https://github.com/tailscale/tailscale
          ref: "v1.68.2"
          shallow: true
          depth: 1
        includePaths:
          - cmd/k8s-operator/deploy/manifests/operator.yaml
        newRootPath: cmd/k8s-operator/deploy/manifests/
        excludePaths:
          - LICENSE
      - path: cert-manager
        http:
          url: https://github.com/cert-manager/cert-manager/releases/download/v1.15.0/cert-manager.yaml
      - path: cloudnative-pg
        http:
          url: https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.23/releases/cnpg-1.23.1.yaml
      - path: rabbitmq-operator
        http:
          url: https://github.com/rabbitmq/cluster-operator/releases/download/v2.9.0/cluster-operator.yml
      - path: contour
        git:
          url: https://github.com/projectcontour/contour
          ref: release-1.29
          shallow: true
          depth: 1
        includePaths:
          - examples/contour/*
        excludePaths:
          - LICENSE
        newRootPath: examples/contour/
  - path: upstream/charts/values
    contents:
      - path: cert-manager
        http:
          url: https://cert-manager.io/docs/installation/best-practice/values.best-practice.yaml
  - path: upstream/charts/network
    contents:
      - path: envoy-gateway
        helmChart:
          name: gateway-helm
          version: "v1.0.2"
          repository:
            url: "oci://docker.io/envoyproxy"
      - path: contour
        helmChart:
          name: contour
          version: "18.2.9"
          repository:
            url: "https://charts.bitnami.com/bitnami"
      - path: tailscale
        helmChart:
          name: tailscale-operator
          version: "1.68.1"
          repository:
            url: "https://pkgs.tailscale.com/helmcharts"
  - path: upstream/charts/security
    contents:
      - path: cert-manager
        helmChart:
          name: cert-manager
          version: "v1.15.0"
          repository:
            url: https://charts.jetstack.io
      - path: trust-manager
        helmChart:
          name: trust-manager
          version: "0.11.0"
          repository:
            url: https://charts.jetstack.io
      - path: cert-manager-csi-driver
        helmChart:
          name: cert-manager
          version: "v0.9.0"
          repository:
            url: https://charts.jetstack.io
      - path: cert-manager-csi-driver-spiffe
        helmChart:
          name: cert-manager-csi-driver-spiffe
          version: "0.7.0"
          repository:
            url: https://charts.jetstack.io
      - path: cert-manager-approver-policy
        helmChart:
          name: cert-manager-approver-policy
          version: "v0.14.1"
          repository:
            url: https://charts.jetstack.io
  - path: upstream/charts/observability
    contents:
      - path: loki
        helmChart:
          name: loki
          version: "6.6.3"
          repository:
            url: https://grafana.github.io/helm-charts
      - path: tempo
        helmChart:
          name: tempo
          version: "1.9.0"
          repository:
            url: https://grafana.github.io/helm-charts
      - path: grafana
        helmChart:
          name: grafana
          version: "8.0.1"
          repository:
            url: https://grafana.github.io/helm-charts
      - path: alloy
        helmChart:
          name: alloy
          version: "0.3.2"
          repository:
            url: https://grafana.github.io/helm-charts
      - path: mimir-distributed
        helmChart:
          name: mimir-distributed
          version: "5.3.0"
          repository:
            url: https://grafana.github.io/helm-charts
  - path: upstream/charts/data
    contents:
      - path: cloudnative-pg
        helmChart:
          name: cloudnative-pg
          version: "0.21.5"
          repository:
            url: https://cloudnative-pg.github.io/charts
      - path: rabbitmq-cluster-operator
        helmChart:
          name: rabbitmq-cluster-operator
          version: "4.3.5"
          repository:
            url: "https://charts.bitnami.com/bitnami"
