apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: static
    contents:
      - path: envoy-gateway
        http:
          url: https://github.com/envoyproxy/gateway/releases/download/v1.0.2/install.yaml
      - path: cert-manager
        http:
          url: https://github.com/cert-manager/cert-manager/releases/download/v1.15.0/cert-manager.yaml
      - path: cloudnative-pg
        http:
          url: https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.23/releases/cnpg-1.23.1.yaml
      - path: rabbitmq-operator
        http:
          url: https://github.com/rabbitmq/cluster-operator/releases/download/v2.9.0/cluster-operator.yml
  - path: charts/network
    contents:
      - path: envoy-gateway
        helmChart:
          name: gateway-helm
          version: "v1.0.2"
          repository:
            url: "oci://docker.io/envoyproxy"
      - path: cert-manager
        helmChart:
          name: cert-manager
          version: "v1.15.0"
          repository:
            url: https://charts.jetstack.io
  - path: charts/observability
    contents:
      - path: loki
        helmChart:
          name: loki
          version: "6.6.3"
          repository:
            url: https://grafana.github.io/helm-charts
      - path: tempo
        helmChart:
          name: tempo
          version: "1.9.0"
          repository:
            url: https://grafana.github.io/helm-charts
      - path: grafana
        helmChart:
          name: grafana
          version: "8.0.1"
          repository:
            url: https://grafana.github.io/helm-charts
      - path: alloy
        helmChart:
          name: alloy
          version: "0.3.2"
          repository:
            url: https://grafana.github.io/helm-charts
      - path: mimir-distributed
        helmChart:
          name: mimir-distributed
          version: "5.3.0"
          repository:
            url: https://grafana.github.io/helm-charts
  - path: charts/data
    contents:
      - path: cloudnative-pg
        helmChart:
          name: cloudnative-pg
          version: "0.21.5"
          repository:
            url: https://cloudnative-pg.github.io/charts
      - path: rabbitmq-cluster-operator
        helmChart:
          name: rabbitmq-cluster-operator
          version: "4.3.5"
          repository:
            url: "https://charts.bitnami.com/bitnami"

