apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: tailscale # class name currently can not be changed
  annotations: {} # we do not support default IngressClass annotation https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class
spec:
  controller: tailscale.com/ts-ingress # controller name currently can not be changed
  # parameters: {} # currently no parameters are supported
