
spring:
  application:
    name: billboard-java-client

# expose all the spring boot actuators good for demos.
# NEVER DO THIS in production
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
---
# configure here is only active when running outside of k8s
spring:
  config:
    activate:
      on-profile:  "!kubernetes"
  cloud:
    discovery:
      client:
        simple:
          instances:
            message-service:
              - uri: "http://localhost:8081"