spring:
  ssl:
    bundle:
      watch:
        file:
          quiet-period: 10s
      options:
        # Legal protocol values are in https://docs.oracle.com/en/java/javase/21/docs/specs/security/standard-names.html#protocols
        enabled-protocols:
          - TLSv1.2
          - TLSv1.3
        # https://docs.oracle.com/en/java/javase/21/docs/specs/security/standard-names.html#jsse-cipher-suite-names
        # recommended list https://developers.cloudflare.com/ssl/reference/cipher-suites/recommendations/
        ciphers:
          # TLS 1.3 cipher suite names
          - TLS_AES_128_GCM_SHA256
          - TLS_AES_256_GCM_SHA384
          - TLS_CHACHA20_POLY1305_SHA256
          # TLS 1.2 cipher suite names
          - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
          - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      pem:
        demo:
          reload-on-update: true
          truststore:
            certificate: "secure/mtls/mtls-client/cert/client.crt"
          keystore:
            certificate: "secure/mtls/mtls-server/cert/server.crt"
            private-key: "secure/mtls/mtls-server/cert/server.key"

server:
  port: 8443
  ssl:
    bundle: "demo"
    client-auth: NEED # set this when the client must use mtls
    # client-auth: WANT # set this when the client can choose to use mtls
    # client-auth: NONE # mtls not supported
