spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/message-service/**
          filters:
            - StripPrefix=2
        - id: billboard-client
          uri: lb://billboard-client
          predicates:
            - Path=/**

# expose all the spring boot actuators good for demos.
# NEVER DO THIS in production
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 9090

---
# configure here is only active when running inside of k8s
spring:
  config:
    activate:
      on-profile: "kubernetes"
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
---
# configure here is only active when running outside of k8s
spring:
  config:
    activate:
      on-profile: "!kubernetes"
  cloud:
    discovery:
      client:
        simple:
          instances:
            billboard-client:
              - uri: "http://localhost:8080"
            message-service:
              - uri: "http://localhost:8081"