spring:
  application:
    name: observation-basics

management:
  observations:
    key-values:
      "service.name" : ${spring.application.name}
      region: "us-east-1"
      stack: "prod"
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
