apiVersion: apps/v1
kind: Deployment
metadata:
  name: billboard
spec:
  selector:
    matchLabels:
      app: billboard
  template:
    metadata:
      labels:
        app: billboard
    spec:
      containers:
        - name: billboard
          image: "billboard:0.0.1-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "768Mi"
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              port: 8082
              path: /actuator/health/liveness
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              port: 8082
              path: /actuator/health/readiness
---
apiVersion: v1
kind: Service
metadata:
  name: billboard
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8082
  selector:
    app: billboard
