FROM eclipse-temurin:24 as builder

# create a custom JRE for the boot application
RUN $JAVA_HOME/bin/jlink \
         --add-modules java.base,java.desktop,java.logging,java.management,java.naming,java.security.jgss,java.instrument,java.sql \
         --strip-debug \
         --no-man-pages \
         --no-header-files \
         --compress=2 \
         --generate-cds-archive \
         --output /javaruntime

# extract the layers of the boot application
WORKDIR application
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=tools -jar application.jar extract --layers --destination /out --application-filename app.jar

# Create an run image for the application
FROM ubuntu:24.04
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH "${JAVA_HOME}/bin:${PATH}"
COPY --from=builder /javaruntime $JAVA_HOME
WORKDIR application
COPY --from=builder /out/dependencies/ ./
COPY --from=builder /out/snapshot-dependencies/ ./
# COPY --from=builder /out/spring-boot-loader/ ./ not needed anymore always empty
COPY --from=builder /out/application/ ./
RUN java -Dspring.aot.enabled=true -Dspring.context.exit=onRefresh -XX:ArchiveClassesAtExit=/application/app.jsa -jar /application/app.jar
ENTRYPOINT ["java","-Dspring.aot.enabled=true", "-XX:SharedArchiveFile=/application/app.jsa","-jar","/application/app.jar"]

