### MVC one event
GET http://localhost:8080/mvc/stream/one
Accept: text/event-stream

### WebFlux one event
GET http://localhost:8080/webflux/stream/one
Accept: text/event-stream

### MVC infinite events
GET http://localhost:8080/mvc/stream/infinite
Accept: text/event-stream

### MVC infinite events
GET http://localhost:8080/webflux/stream/infinite
Accept: text/event-stream

### Asyc Servlet success
GET http://localhost:8080/servlet/async?count=8
Accept: text/event-stream

### Asyc Servlet failure due to 10 second timetout
GET http://localhost:8080/servlet/async?count=80
Accept: text/event-stream

### Create a new watchlist stream for AAPL
POST http://localhost:8080/watchlist
Content-Type: application/json
Accept: text/event-stream

{
  "symbol": "AAPL"
}

### Place a buy order that should be purchased right away
POST http://localhost:8080/orders
Content-Type: application/json

{
  "symbol": "AAPL",
  "quantity": "10",
  "maxPrice": 190.00
}


### Place a buy order that should be purchased right away
POST http://localhost:8080/orders
Content-Type: application/json

{
  "symbol": "AAPL",
  "quantity": "10",
  "maxPrice": 101.00
}

### Resume Stream
GET http://localhost:8080/orders
Last-Event-Id: aapl.a4439ab4-20a6-4ef6-9b13-e17a78ed0e44_0

### Test Redirect
GET http://localhost:8080/test/redirect?symbol=APPL
