### MVC one event
GET http://localhost:8080/mvc/stream/one
Accept: text/event-stream

### WebFlux one event
GET http://localhost:8080/webflux/stream/one
Accept: text/event-stream

### MVC infinite events
GET http://localhost:8080/mvc/stream/infinite
Accept: text/event-stream

### MVC infinite events
GET http://localhost:8080/webflux/stream/infinite
Accept: text/event-stream

### Asyc Servlet success
GET http://localhost:8080/servlet/async?count=8
Accept: text/event-stream

### Asyc Servlet failure due to 10 second timetout
GET http://localhost:8080/servlet/async?count=80
Accept: text/event-stream

### Create a new watchlist stream for AAPL
POST http://localhost:8080/watchlist
Content-Type: application/json
Accept: text/event-stream

{
  "symbol": "AAPL"
}
