spring:
  application:
    # name of the application that is used to identify the app to the config server
    name: billboard
  config:
    import: "configserver:http://localhost:8888" # only works in boot 2.4 or later
    #import: "optional:configserver:http://localhost:8888" # adding optional allows app to startup even if config server is not available
