apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: discovery-dns

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - dns-message-service/k8s/message-service.yaml
  - dns-billboard-client/k8s/billboard-client.yaml

