spring:
  main:
    web-application-type: none
  ssl:
    bundle:
      watch:
        file:
          quiet-period: 10s
      options:
        # Legal protocol values are in https://docs.oracle.com/en/java/javase/21/docs/specs/security/standard-names.html#protocols
        enabled-protocols:
          - TLSv1.2
          - TLSv1.3
        # https://docs.oracle.com/en/java/javase/21/docs/specs/security/standard-names.html#jsse-cipher-suite-names
        # recommended list https://developers.cloudflare.com/ssl/reference/cipher-suites/recommendations/
        ciphers:
          # TLS 1.3 cipher suite names
          - TLS_AES_128_GCM_SHA256
          - TLS_AES_256_GCM_SHA384
          - TLS_CHACHA20_POLY1305_SHA256
          # TLS 1.2 cipher suite names
          - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
          - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      pem:
        client:
          reload-on-update: true
          truststore:
            certificate:  "secure/tls/mtls/mtls-server/cert/server.crt"
          keystore:
            certificate: "secure/tls/mtls/mtls-client/cert/client.crt" # required because the server is using self signed certificates
            private-key: "secure/tls/mtls/mtls-client/cert/client.key"

logging:
  level:
    root: info
