apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
spec:
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: "gateway-server:0.0.1-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "768Mi"
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              port: 9090
              path: /actuator/health/liveness
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              port: 9090
              path: /actuator/health/readiness
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app: gateway-server
