---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-cloud

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-cloud
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-cloud
subjects:
  - kind: ServiceAccount
    name: spring-cloud
    apiGroup: ""
roleRef:
  kind: Role
  name: spring-cloud
  apiGroup: ""
