apiVersion: apps/v1
kind: Deployment
metadata:
  name: billboard-client
spec:
  selector:
    matchLabels:
      app: billboard-client
  template:
    metadata:
      labels:
        app: billboard-client
    spec:
      containers:
        - name: billboard-client
          image: "native-billboard-client:0.0.1-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "768Mi"
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              port: 8080
              path: /actuator/health/readiness
---
apiVersion: v1
kind: Service
metadata:
  name: billboard-client
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: billboard-client
