apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
spec:
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
        - name: message-service
          image: "eureka-message-service:0.0.1-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          env:
            - name: "SERVER_PORT" #required because otherwise the service will start on a random port that k8s does not know about
              value: "8080"
            - name: "eureka_client_serviceUrl_defaultZone"
              value: "http://eureka-server:8761/eureka"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              port: 8080
              path: /actuator/health/readiness
---
apiVersion: v1
kind: Service
metadata:
  name: message-service
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: message-service
